stages:
  - Build
  - Test
  - Deploy

build:
  stage: Build
  tags:
    - docker
  script:
    - ls
    - docker build -t $REGISTRY .
  allow_failure: true

unittest:
  stage: Test
  tags:
    - shell
  script:
    - echo "test"
    - exit 1
  allow_failure: true

deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "deploy"
    - exit 1
  allow_failure: true
