stages:
  - Build
  - Test

build:
  stage: Build
  tags:
    - shell
  script:
    - docker build -t software_image -f ./Dockerfiles/software_dockerfile .
  allow_failure: true

unittest:
  stage: Test
  tags:
    - shell
  script:
    - echo "To be implemented when needed"
    - exit 0
  allow_failure: true
