stages:
  - Build
  - Test
  - Deploy

build:
  stage: Build
  image: alpine:latest
  tags:
    - shell
  script:
    - RUN pio run --target clean
    - RUN pio run
  allow_failure: true

unittest:
  stage: Test
  tags:
    - shell
  script:
    - echo "test"
    - exit 1
  allow_failure: true

deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "deploy"
    - exit 1
  allow_failure: true
