stages:
  - Build
  - Test

build:
  stage: Build
  tags:
    - shell
  script:
    - docker build -f ./dockerfile1 .
  allow_failure: true

unittest:
  stage: Test
  tags:
    - shell
  script:
    - echo "test"
    - exit 1
  allow_failure: true
