stages:
  - Build
  - Test
  - Deploy

build:
  stage: Build
  image: Dockerfile
  tags:
    - shell
  script:
    - docker build -t the-docker-image .
  allow_failure: true

unittest:
  stage: Test
  tags:
    - shell
  script:
    - echo "test"
    - exit 1
  allow_failure: true

deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "deploy"
    - exit 1
  allow_failure: true
